### ISSUE TITLE
Angabe von CNC-Nutzungen

### ISSUE THREAD

**Issue by mdrobisch** [konglomerat/roseguarden#89]
# Angabe der CNC-Nutzung

Als Registirierter Nutzer oder Gast
möchte ich, meine CNC-Nutzung eintragen können
damit ich eine Reichnung für die angefallenen CNC-Kosten erhalten kann.

## Akzeptanzkriterien

* Ähnliche UX und Vorgehen wie in #87 
* Der Nutzer muss die Angaben entsprechend der Vorgaben aus der CNC-Gruppe (Todo siehe unten) eingeben können
* Aus den Eingaben soll Preis vor dem abesenden ersichtlich werden. Berechnungsgrundlage entsprechend der Vorgaben aus der CNC-Gruppe
* Gäste (ohne Anmeldung / Registirung) sollen ihre Lasernutzung mit Angabe ihrer eMail-Adresse einreichen können.
* Nutzer und Gäste müssen die bestehenden Nutzungsbedingungen und Datenschutzerklärungen 

## Technische Bemerkungen

* Die Implementierung soll in den bestehenden Invoices-Workspace erfolgen

## Todos

- [ ] Einholen der Vorgaben aus der CNC-Gruppe
  - Ansprechpartner ?
- [ ] Formular zur Eingabe der Nutzungsdetails entsprechen der Vorgaben
- [ ] Berechnung der Preise entsprechend der Vorgaben
- [ ] Anbindung an die "Consumption"-API im "Invoice" Workspace

**Comment by makakken** [comment]
@mdrobisch ich würde mich darum kümmern die entsprechenden Infos der Lasergruppe einzuholen, ok?
